name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows:latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build Executable
        run: |
          pyinstaller main_windows.spec
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: dist/main.exe